@Blog.Api_HostAddress = https://localhost:7000

### List published posts
GET {{Blog.Api_HostAddress}}/api/posts
Accept: application/json

### Get a post by slug
GET {{Blog.Api_HostAddress}}/api/posts/hello-world
Accept: application/json
