// <auto-generated />
using System;
using Blog.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Api.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20260802094302_SeedDummyPosts")]
    partial class SeedDummyPosts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blog.Api.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "# Welcome\n\nThis is the very first post on this deliberately small blog. It's built with **ASP.NET Core** on the backend and **React + TypeScript** on the front end.\n\nFeel free to look around!",
                            CreatedAt = new DateTime(2026, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "welcome-to-my-blog",
                            Title = "Welcome to My Blog",
                            UpdatedAt = new DateTime(2026, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Content = "# Markdown 101\n\nPosts here are authored in Markdown. A few basics:\n\n- **Bold** and _italic_ text\n- Lists, like this one\n- `inline code` and fenced code blocks\n\n```csharp\nConsole.WriteLine(\"Hello, blog!\");\n```\n",
                            CreatedAt = new DateTime(2026, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "getting-started-with-markdown",
                            Title = "Getting Started with Markdown",
                            UpdatedAt = new DateTime(2026, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Content = "# Motivation\n\nI wanted a minimal place to write, without a heavyweight CMS. This project pairs a small Web API with Azure SQL storage and Entra ID sign-in so only I can publish, while everyone can read.",
                            CreatedAt = new DateTime(2026, 1, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "why-i-built-this-blog",
                            Title = "Why I Built This Blog",
                            UpdatedAt = new DateTime(2026, 1, 3, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Content = "# Backlog\n\nA scratchpad of things I might write about:\n\n1. Deploying to Azure\n2. EF Core migrations tips\n3. Securing an API with app roles\n\n_This is an unpublished draft._",
                            CreatedAt = new DateTime(2026, 1, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = false,
                            Slug = "draft-ideas-for-upcoming-posts",
                            Title = "Draft: Ideas for Upcoming Posts",
                            UpdatedAt = new DateTime(2026, 1, 4, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
