// <auto-generated />
using System;
using Blog.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Api.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20260808034508_AddGitHubBlogSyncFields")]
    partial class AddGitHubBlogSyncFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blog.Api.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<int?>("SourceNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("SourceNumber")
                        .IsUnique()
                        .HasFilter("[SourceNumber] IS NOT NULL");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "# Welcome\n\nThis is the very first post on this deliberately small blog. It's built with **ASP.NET Core** on the backend and **React + TypeScript** on the front end.\n\nFeel free to look around!",
                            CreatedAt = new DateTime(2026, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "welcome-to-my-blog",
                            Title = "Welcome to My Blog",
                            UpdatedAt = new DateTime(2026, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Content = "# Markdown 101\n\nPosts here are authored in Markdown. A few basics:\n\n- **Bold** and _italic_ text\n- Lists, like this one\n- `inline code` and fenced code blocks\n\n```csharp\nConsole.WriteLine(\"Hello, blog!\");\n```\n",
                            CreatedAt = new DateTime(2026, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "getting-started-with-markdown",
                            Title = "Getting Started with Markdown",
                            UpdatedAt = new DateTime(2026, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Content = "# Motivation\n\nI wanted a minimal place to write, without a heavyweight CMS. This project pairs a small Web API with Azure SQL storage and Entra ID sign-in so only I can publish, while everyone can read.",
                            CreatedAt = new DateTime(2026, 1, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "why-i-built-this-blog",
                            Title = "Why I Built This Blog",
                            UpdatedAt = new DateTime(2026, 1, 3, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Content = "# Backlog\n\nA scratchpad of things I might write about:\n\n1. Deploying to Azure\n2. EF Core migrations tips\n3. Securing an API with app roles\n\n_This is an unpublished draft._",
                            CreatedAt = new DateTime(2026, 1, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = false,
                            Slug = "draft-ideas-for-upcoming-posts",
                            Title = "Draft: Ideas for Upcoming Posts",
                            UpdatedAt = new DateTime(2026, 1, 4, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Content = "# Understanding Async and Await in C#\n\nThis is a placeholder post about understanding async and await in c#. Real content coming soon — for now it exists to demonstrate pagination.",
                            CreatedAt = new DateTime(2026, 1, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "understanding-async-and-await-in-c",
                            Title = "Understanding Async and Await in C#",
                            UpdatedAt = new DateTime(2026, 1, 5, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Content = "# A Practical Tour of LINQ\n\nThis is a placeholder post about a practical tour of linq. Real content coming soon — for now it exists to demonstrate pagination.",
                            CreatedAt = new DateTime(2026, 1, 6, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "a-practical-tour-of-linq",
                            Title = "A Practical Tour of LINQ",
                            UpdatedAt = new DateTime(2026, 1, 6, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Content = "# Dependency Injection Explained\n\nThis is a placeholder post about dependency injection explained. Real content coming soon — for now it exists to demonstrate pagination.",
                            CreatedAt = new DateTime(2026, 1, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "dependency-injection-explained",
                            Title = "Dependency Injection Explained",
                            UpdatedAt = new DateTime(2026, 1, 7, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Content = "# Entity Framework Core Migrations Tips\n\nThis is a placeholder post about entity framework core migrations tips. Real content coming soon — for now it exists to demonstrate pagination.",
                            CreatedAt = new DateTime(2026, 1, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "entity-framework-core-migrations-tips",
                            Title = "Entity Framework Core Migrations Tips",
                            UpdatedAt = new DateTime(2026, 1, 8, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Content = "# Building Minimal APIs in ASP.NET Core\n\nThis is a placeholder post about building minimal apis in asp.net core. Real content coming soon — for now it exists to demonstrate pagination.",
                            CreatedAt = new DateTime(2026, 1, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "building-minimal-apis-in-aspnet-core",
                            Title = "Building Minimal APIs in ASP.NET Core",
                            UpdatedAt = new DateTime(2026, 1, 9, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Content = "# React Hooks You Should Know\n\nThis is a placeholder post about react hooks you should know. Real content coming soon — for now it exists to demonstrate pagination.",
                            CreatedAt = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "react-hooks-you-should-know",
                            Title = "React Hooks You Should Know",
                            UpdatedAt = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            Content = "# TypeScript Generics Made Simple\n\nThis is a placeholder post about typescript generics made simple. Real content coming soon — for now it exists to demonstrate pagination.",
                            CreatedAt = new DateTime(2026, 1, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "typescript-generics-made-simple",
                            Title = "TypeScript Generics Made Simple",
                            UpdatedAt = new DateTime(2026, 1, 11, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            Content = "# State Management Without a Library\n\nThis is a placeholder post about state management without a library. Real content coming soon — for now it exists to demonstrate pagination.",
                            CreatedAt = new DateTime(2026, 1, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "state-management-without-a-library",
                            Title = "State Management Without a Library",
                            UpdatedAt = new DateTime(2026, 1, 12, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            Content = "# Styling with Modern CSS\n\nThis is a placeholder post about styling with modern css. Real content coming soon — for now it exists to demonstrate pagination.",
                            CreatedAt = new DateTime(2026, 1, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "styling-with-modern-css",
                            Title = "Styling with Modern CSS",
                            UpdatedAt = new DateTime(2026, 1, 13, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            Content = "# Debugging Like a Pro\n\nThis is a placeholder post about debugging like a pro. Real content coming soon — for now it exists to demonstrate pagination.",
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "debugging-like-a-pro",
                            Title = "Debugging Like a Pro",
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            Content = "# Writing Better Git Commit Messages\n\nThis is a placeholder post about writing better git commit messages. Real content coming soon — for now it exists to demonstrate pagination.",
                            CreatedAt = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "writing-better-git-commit-messages",
                            Title = "Writing Better Git Commit Messages",
                            UpdatedAt = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            Content = "# An Introduction to Docker\n\nThis is a placeholder post about an introduction to docker. Real content coming soon — for now it exists to demonstrate pagination.",
                            CreatedAt = new DateTime(2026, 1, 16, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "an-introduction-to-docker",
                            Title = "An Introduction to Docker",
                            UpdatedAt = new DateTime(2026, 1, 16, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            Content = "# Deploying to Azure App Service\n\nThis is a placeholder post about deploying to azure app service. Real content coming soon — for now it exists to demonstrate pagination.",
                            CreatedAt = new DateTime(2026, 1, 17, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "deploying-to-azure-app-service",
                            Title = "Deploying to Azure App Service",
                            UpdatedAt = new DateTime(2026, 1, 17, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            Content = "# Caching Strategies for Web Apps\n\nThis is a placeholder post about caching strategies for web apps. Real content coming soon — for now it exists to demonstrate pagination.",
                            CreatedAt = new DateTime(2026, 1, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "caching-strategies-for-web-apps",
                            Title = "Caching Strategies for Web Apps",
                            UpdatedAt = new DateTime(2026, 1, 18, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            Content = "# Securing Your REST API\n\nThis is a placeholder post about securing your rest api. Real content coming soon — for now it exists to demonstrate pagination.",
                            CreatedAt = new DateTime(2026, 1, 19, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "securing-your-rest-api",
                            Title = "Securing Your REST API",
                            UpdatedAt = new DateTime(2026, 1, 19, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            Content = "# Unit Testing Fundamentals\n\nThis is a placeholder post about unit testing fundamentals. Real content coming soon — for now it exists to demonstrate pagination.",
                            CreatedAt = new DateTime(2026, 1, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "unit-testing-fundamentals",
                            Title = "Unit Testing Fundamentals",
                            UpdatedAt = new DateTime(2026, 1, 20, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            Content = "# Working with JSON in .NET\n\nThis is a placeholder post about working with json in .net. Real content coming soon — for now it exists to demonstrate pagination.",
                            CreatedAt = new DateTime(2026, 1, 21, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "working-with-json-in-net",
                            Title = "Working with JSON in .NET",
                            UpdatedAt = new DateTime(2026, 1, 21, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            Content = "# Optimizing Frontend Performance\n\nThis is a placeholder post about optimizing frontend performance. Real content coming soon — for now it exists to demonstrate pagination.",
                            CreatedAt = new DateTime(2026, 1, 22, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "optimizing-frontend-performance",
                            Title = "Optimizing Frontend Performance",
                            UpdatedAt = new DateTime(2026, 1, 22, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            Content = "# Clean Code Principles\n\nThis is a placeholder post about clean code principles. Real content coming soon — for now it exists to demonstrate pagination.",
                            CreatedAt = new DateTime(2026, 1, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "clean-code-principles",
                            Title = "Clean Code Principles",
                            UpdatedAt = new DateTime(2026, 1, 23, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            Content = "# My Favorite Developer Tools\n\nThis is a placeholder post about my favorite developer tools. Real content coming soon — for now it exists to demonstrate pagination.",
                            CreatedAt = new DateTime(2026, 1, 24, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "my-favorite-developer-tools",
                            Title = "My Favorite Developer Tools",
                            UpdatedAt = new DateTime(2026, 1, 24, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            Content = "# 你好，世界！\n\n这是一篇用于测试**中文字符兼容性**的文章。如果你能正常阅读这段文字，说明数据库、接口和前端都能正确处理 UTF-8 编码。\n\n## 常见标点\n\n逗号，句号。感叹号！问号？分号；冒号：引号「你好」『世界』，还有省略号……\n\n## 列表\n\n- 苹果 🍎\n- 香蕉 🍌\n- 西瓜 🍉\n\n## 代码\n\n```csharp\nConsole.WriteLine(\"你好，世界\");\n```\n\n> 引用：路漫漫其修远兮，吾将上下而求索。\n",
                            CreatedAt = new DateTime(2026, 1, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "chinese-hello-world",
                            Title = "你好，世界：中文博客测试",
                            UpdatedAt = new DateTime(2026, 1, 25, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            Content = "# 前端开发笔记\n\n在现代前端项目中，**React** 搭配 **TypeScript** 已经成为主流选择。类型系统能在编译期发现许多潜在的错误。\n\n## 一个简单的组件\n\n```tsx\ninterface Props {\n  名称: string;\n}\n\nexport function 问候({ 名称 }: Props) {\n  return <p>你好，{名称}！</p>;\n}\n```\n\n## 小结\n\n1. 组件应保持单一职责。\n2. 尽量复用逻辑。\n3. 为公共接口编写类型。\n",
                            CreatedAt = new DateTime(2026, 1, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "frontend-notes-react-typescript",
                            Title = "前端开发笔记：React 与 TypeScript",
                            UpdatedAt = new DateTime(2026, 1, 26, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            Content = "# 异步编程\n\n在 .NET 中，`async` 和 `await` 让编写非阻塞代码变得简单直观。\n\n| 关键字 | 含义 |\n| --- | --- |\n| `async` | 标记一个异步方法 |\n| `await` | 等待异步操作完成 |\n\n```csharp\npublic async Task<string> 获取数据Async()\n{\n    await Task.Delay(100);\n    return \"完成\";\n}\n```\n\n**注意**：不要在异步方法中使用 `.Result`，否则可能导致死锁。\n",
                            CreatedAt = new DateTime(2026, 1, 27, 12, 0, 0, 0, DateTimeKind.Utc),
                            Published = true,
                            Slug = "dotnet-csharp-async",
                            Title = "深入理解 .NET 与 C# 的异步编程",
                            UpdatedAt = new DateTime(2026, 1, 27, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Blog.Api.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = ".NET",
                            Slug = "dotnet"
                        },
                        new
                        {
                            Id = 2,
                            Name = "C#",
                            Slug = "csharp"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ASP.NET Core",
                            Slug = "aspnet-core"
                        },
                        new
                        {
                            Id = 4,
                            Name = "React",
                            Slug = "react"
                        },
                        new
                        {
                            Id = 5,
                            Name = "TypeScript",
                            Slug = "typescript"
                        },
                        new
                        {
                            Id = 6,
                            Name = "CSS",
                            Slug = "css"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Azure",
                            Slug = "azure"
                        },
                        new
                        {
                            Id = 8,
                            Name = "DevOps",
                            Slug = "devops"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Testing",
                            Slug = "testing"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Performance",
                            Slug = "performance"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Best Practices",
                            Slug = "best-practices"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Git",
                            Slug = "git"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Docker",
                            Slug = "docker"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Database",
                            Slug = "database"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Tutorial",
                            Slug = "tutorial"
                        },
                        new
                        {
                            Id = 16,
                            Name = "教程",
                            Slug = "jiaocheng"
                        },
                        new
                        {
                            Id = 17,
                            Name = "前端",
                            Slug = "qianduan"
                        });
                });

            modelBuilder.Entity("PostTag", b =>
                {
                    b.Property<int>("PostsId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("PostsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("PostTag");

                    b.HasData(
                        new
                        {
                            PostsId = 1,
                            TagsId = 2
                        },
                        new
                        {
                            PostsId = 1,
                            TagsId = 12
                        },
                        new
                        {
                            PostsId = 1,
                            TagsId = 15
                        },
                        new
                        {
                            PostsId = 2,
                            TagsId = 4
                        },
                        new
                        {
                            PostsId = 2,
                            TagsId = 5
                        },
                        new
                        {
                            PostsId = 3,
                            TagsId = 2
                        },
                        new
                        {
                            PostsId = 3,
                            TagsId = 15
                        },
                        new
                        {
                            PostsId = 4,
                            TagsId = 4
                        },
                        new
                        {
                            PostsId = 4,
                            TagsId = 5
                        },
                        new
                        {
                            PostsId = 4,
                            TagsId = 12
                        },
                        new
                        {
                            PostsId = 5,
                            TagsId = 2
                        },
                        new
                        {
                            PostsId = 5,
                            TagsId = 8
                        },
                        new
                        {
                            PostsId = 6,
                            TagsId = 7
                        },
                        new
                        {
                            PostsId = 6,
                            TagsId = 11
                        },
                        new
                        {
                            PostsId = 7,
                            TagsId = 6
                        },
                        new
                        {
                            PostsId = 7,
                            TagsId = 12
                        },
                        new
                        {
                            PostsId = 8,
                            TagsId = 7
                        },
                        new
                        {
                            PostsId = 9,
                            TagsId = 1
                        },
                        new
                        {
                            PostsId = 9,
                            TagsId = 3
                        },
                        new
                        {
                            PostsId = 9,
                            TagsId = 12
                        },
                        new
                        {
                            PostsId = 10,
                            TagsId = 9
                        },
                        new
                        {
                            PostsId = 10,
                            TagsId = 14
                        },
                        new
                        {
                            PostsId = 11,
                            TagsId = 3
                        },
                        new
                        {
                            PostsId = 11,
                            TagsId = 6
                        },
                        new
                        {
                            PostsId = 11,
                            TagsId = 7
                        },
                        new
                        {
                            PostsId = 12,
                            TagsId = 8
                        },
                        new
                        {
                            PostsId = 12,
                            TagsId = 15
                        },
                        new
                        {
                            PostsId = 13,
                            TagsId = 11
                        },
                        new
                        {
                            PostsId = 14,
                            TagsId = 9
                        },
                        new
                        {
                            PostsId = 15,
                            TagsId = 9
                        },
                        new
                        {
                            PostsId = 15,
                            TagsId = 11
                        },
                        new
                        {
                            PostsId = 16,
                            TagsId = 2
                        },
                        new
                        {
                            PostsId = 17,
                            TagsId = 3
                        },
                        new
                        {
                            PostsId = 17,
                            TagsId = 4
                        },
                        new
                        {
                            PostsId = 18,
                            TagsId = 5
                        },
                        new
                        {
                            PostsId = 18,
                            TagsId = 8
                        },
                        new
                        {
                            PostsId = 18,
                            TagsId = 9
                        },
                        new
                        {
                            PostsId = 19,
                            TagsId = 3
                        },
                        new
                        {
                            PostsId = 19,
                            TagsId = 9
                        },
                        new
                        {
                            PostsId = 20,
                            TagsId = 3
                        },
                        new
                        {
                            PostsId = 20,
                            TagsId = 7
                        },
                        new
                        {
                            PostsId = 21,
                            TagsId = 4
                        },
                        new
                        {
                            PostsId = 21,
                            TagsId = 7
                        },
                        new
                        {
                            PostsId = 22,
                            TagsId = 13
                        },
                        new
                        {
                            PostsId = 22,
                            TagsId = 14
                        },
                        new
                        {
                            PostsId = 23,
                            TagsId = 15
                        },
                        new
                        {
                            PostsId = 24,
                            TagsId = 2
                        },
                        new
                        {
                            PostsId = 24,
                            TagsId = 9
                        },
                        new
                        {
                            PostsId = 25,
                            TagsId = 16
                        },
                        new
                        {
                            PostsId = 25,
                            TagsId = 15
                        },
                        new
                        {
                            PostsId = 26,
                            TagsId = 17
                        },
                        new
                        {
                            PostsId = 26,
                            TagsId = 4
                        },
                        new
                        {
                            PostsId = 26,
                            TagsId = 5
                        },
                        new
                        {
                            PostsId = 27,
                            TagsId = 16
                        },
                        new
                        {
                            PostsId = 27,
                            TagsId = 1
                        },
                        new
                        {
                            PostsId = 27,
                            TagsId = 2
                        });
                });

            modelBuilder.Entity("PostTag", b =>
                {
                    b.HasOne("Blog.Api.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Api.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
